### ISSUE TITLE
Possible meta issue on container->get()

### ISSUE THREAD

**Issue by GDmac** [capsulephp/di#5]
using capsule 2.x and trying the .phpstorm.meta.php 
It does recognise the return-type for ```$container->new(Foo::class)```
but it seems completely lost for ```$container->get(Foo::class);```

![phpstorm meta bug](https://user-images.githubusercontent.com/156334/141282266-5f4b6627-b340-4558-92f1-31ec52377278.jpeg)

Can you verify/check this? Is this a phpstorm bug?

- It does seem to work if i rename the get method
- it does resolve for a quick hand-crafted container
   (meta still doesn't recognize the get() method)

```php
class TestClass {
    public $prop = "FooBar";
}
class TestContainer {
    private $item = [];
    public function new($id) {
        return new $id();
    }
    public function get(string $id) {
        if (!$this->has($id)) $this->item[$id] = $this->new($id);
        return $this->item[$id];
    }
    public function has($id) {
        return (isset($this->item[$id]));
    }
}
$di = new TestContainer();
$sut = $di->get(TestClass::class);
echo $sut->prop; // <-- hover over prop shows '$prop = "FooBar" string
```

**Comment by pmjones** [comment]
I rarely use PHPStorm myself; having said that, I did try the metafile on a trial copy a couple years ago, and it worked then.

I just now downloaded a trial of the newest PHPStorm (2021.2), and it seems to be working here. I coped the phpstorm.meta.php file (adding a leading dot) to the root of the DI package, created a test file, and got this:

![Screen Shot 2021-11-11 at 08 10 54](https://user-images.githubusercontent.com/25754/141312454-bd2e42df-a600-4cdf-a9c0-ff7910eb653f.png)

Maybe I am misunderstanding PHPStorm somehow?

**Comment by GDmac** [comment]
🤔 that's because Definition is already defined as the return type.
Here is with an arbitrary class for ->get (not working) and new (does work, shows $prop)

![meta-get-fail](https://user-images.githubusercontent.com/156334/141359973-6df8ac9a-1af6-4abf-ac86-f9048e925ea8.jpg)

![meta-get-fail2](https://user-images.githubusercontent.com/156334/141359990-6bc09c34-7348-47d3-b32a-cbd5a5abb38c.jpg)

**Comment by pmjones** [comment]
> Definition is already defined as the return type.

Oh of course. All right, I will dig deeper into it. Thanks for your patience!

**Comment by GDmac** [comment]
I'm convinced it's a phpstorm bug, 
if i add a docblock it (oddly) seems fixed.
(bug already reported here: https://youtrack.jetbrains.com/issue/WI-63899)

```php
    /**
     * @param string $id
     * @return mixed
     * @throws NotFoundException
     */
    public function get($id)
    {
        if (! isset($this->instances[$id])) {
            $this->instances[$id] = $this->new($id);
        }

        return $this->instances[$id];
    }
```

![phpstorm-meta-bug-fix](https://user-images.githubusercontent.com/156334/141363802-29465c20-f8cf-4160-af52-2230d908084b.jpg)

**Comment by GDmac** [comment]
Bug report amended/explained
https://youtrack.jetbrains.com/issue/WI-63899#focus=Comments-27-5433231.0-0

**Comment by pmjones** [comment]
Thanks for tracking it with them @GDmac !

**Comment by GDmac** [comment]
bug reported, we'll wait for IDE's to catch up.
